// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwOfHE7boIXjso5cOdPxShQ958UI30-pc',
    appId: '1:1076555859170:android:225647c9f27fc0f87d8abb',
    messagingSenderId: '1076555859170',
    projectId: 'flutter-mobile-app-9cdb2',
    storageBucket: 'flutter-mobile-app-9cdb2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBE6KoeacDA2YaFuNuwP3-3R41TJjogU7A',
    appId: '1:1076555859170:ios:c3b8e85e17df4f267d8abb',
    messagingSenderId: '1076555859170',
    projectId: 'flutter-mobile-app-9cdb2',
    storageBucket: 'flutter-mobile-app-9cdb2.firebasestorage.app',
    iosBundleId: 'com.example.quizFlApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCVb6M_ypkliKnxnmxObTOVvWwOeXkXJY',
    appId: '1:1076555859170:web:6c315991209a60f67d8abb',
    messagingSenderId: '1076555859170',
    projectId: 'flutter-mobile-app-9cdb2',
    authDomain: 'flutter-mobile-app-9cdb2.firebaseapp.com',
    storageBucket: 'flutter-mobile-app-9cdb2.firebasestorage.app',
  );
}
